name: Tests
on:
  push:
    branches:
    pull_request:

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup
        run: |
          make setup

      - name: Lint
        run: |
          make lint

      - name: Unit tests
        run: |
          make test

